language: node_js
cache: yarn
node_js:
  - '8'
script:
  - cd app-backend && yarn && yarn run test
  - cd ../app-client && yarn && yarn run test
  - cd ../ && yarn && yarn run test
notifications:
  email: false
